"""Headscale v0.25 cell config generation (pinned upstream schema facts).

Merge unit B (THR-097, TASK-5792). Emits an independent, loopback-bound
``config.yaml`` per cell with the v0.25 schema verified against the pinned
upstream ``config-example.yaml``:

- ``prefixes`` is the MAP form (``v4`` / ``v6`` / ``allocation``) — the list
  form is a schema error and must never be emitted;
- MagicDNS is explicitly disabled with a lab-only ``base_domain`` (the
  deprecated ``dns.override_local_dns`` key is never emitted);
- policy is file-mode with a per-cell path;
- database is per-cell sqlite3; the Noise key is per-cell;
- optional shared DERP region (same region id for both cells — the shared
  fleet, cell-scoped policy boundary).
"""
from __future__ import annotations

import re as _re
from pathlib import Path

from .models import CellSpec

LAB_BASE_DOMAIN = "lab.invalid"
# Inside the cell container the run state dir is bind-mounted here; config
# paths must reference container paths, never host paths.
CONTAINER_STATE_DIR = "/var/lib/headscale"


def container_path(host_path: Path, state_dir: Path) -> str:
    """Map a host-side state path to the path the cell container sees.

    ``state_dir`` is bind-mounted at ``/var/lib/headscale``; every identity
    file (noise key, database, policy) must be referenced by its container
    path inside ``config.yaml``.
    """
    rel = Path(host_path).resolve().relative_to(Path(state_dir).resolve())
    return f"{CONTAINER_STATE_DIR}/{rel}"


def headscale_config_text(
    cell: CellSpec,
    policy_path: Path,
    derp_enabled: bool = True,
) -> str:
    """Render the cell's headscale v0.25 config as YAML text (stdlib emitter).

    All identity paths are container-mapped (the run state dir is bind-mounted
    at ``/var/lib/headscale``). The embedded DERP server is ENABLED: headscale
    v0.25.1 refuses to boot with an empty DERPMap ("initial DERPMap is empty,
    Headscale requires at least one entry"), so every cell advertises a
    loopback-only embedded DERP region (per-cell STUN listener, per-cell DERP
    private key, auto-added to the map). Clients cannot relay through it —
    tailscale always connects to DERP over TLS while the lab ``server_url`` is
    loopback http — so no relay path is established, DERP isolation is never
    claimed, and relay-forced cases stay ``not-executed-prerequisite``.
    """
    derp_block = ""
    if derp_enabled:
        derp_block = f"""
derp:
  server:
    enabled: true
    region_id: {cell.derp_region_id}
    region_code: "lab"
    region_name: "HappyRanch Lab DERP"
    stun_listen_addr: "127.0.0.1:{cell.stun_port}"
    private_key_path: {CONTAINER_STATE_DIR}/derp_server_private.key
    automatically_add_embedded_derp_region: true
"""
    return f"""# Generated by the hostile tenant-isolation lab harness (THR-097 unit B).
# Cell {cell.cell_id} (tenant {cell.tenant_id}) — loopback-only lab identity.
server_url: {cell.server_url}
listen_addr: 127.0.0.1:{cell.control_port}
metrics_listen_addr: 127.0.0.1:{cell.control_port + 1000}

noise:
  private_key_path: {container_path(cell.key_path, cell.state_dir)}

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

database:
  type: sqlite3
  path: {container_path(cell.db_path, cell.state_dir)}

policy:
  mode: file
  path: {container_path(policy_path, cell.state_dir)}

dns:
  magic_dns: false
  base_domain: {LAB_BASE_DOMAIN}
  nameservers:
    global: []

log:
  format: text
  level: info
{derp_block}"""


def validate_config_schema(text: str) -> None:
    """Fail closed unless the emitted config matches the pinned v0.25 schema.

    Structural checks mirror the upstream config-example.yaml facts: map-form
    prefixes, MagicDNS off with base_domain, file-mode policy path, sqlite db,
    per-cell noise key, container-mapped identity paths, loopback binds.
    """
    assert "prefixes:" in text and "  v4: " in text and "  v6: " in text, (
        "config must use the v0.25 MAP-form prefixes.v4/prefixes.v6"
    )
    assert "  - 100.64.0.0/10" not in text, "list-form prefixes are a schema error"
    assert "magic_dns: false" in text, "MagicDNS must be explicitly disabled (v0.25 fatals without base_domain)"
    assert "override_local_dns" not in text, "deprecated dns.override_local_dns must never be emitted"
    assert f"base_domain: {LAB_BASE_DOMAIN}" in text, "lab base_domain required when MagicDNS disabled"
    assert "mode: file" in text and "path: " in text, "file-mode policy path required"
    assert "type: sqlite3" in text, "per-cell sqlite3 database required"
    assert "noise:" in text and "private_key_path:" in text, "per-cell Noise key required"
    assert f"private_key_path: {CONTAINER_STATE_DIR}/" in text, (
        "noise key path must be container-mapped (host paths break the container)"
    )
    assert f"path: {CONTAINER_STATE_DIR}/db.sqlite" in text, (
        "database path must be container-mapped"
    )
    assert f"path: {CONTAINER_STATE_DIR}/policy.json" in text, (
        "policy path must be container-mapped"
    )
    assert "0.0.0.0" not in text, "cells must bind loopback only"
    assert "server_url: http://127.0.0.1:" in text, "server_url must be lab-loopback"
    assert "listen_addr: 127.0.0.1:" in text, "listen_addr must be lab-loopback"
    # headscale v0.25.1 refuses to boot with an empty DERPMap (app.go:
    # errEmptyInitialDERPMap "initial DERPMap is empty, Headscale requires at
    # least one entry"). The embedded DERP server must be enabled, with a
    # loopback STUN listener, a container-mapped DERP private key, and the
    # region auto-added — otherwise the cell can never start.
    assert "derp:" in text, "config must carry the embedded DERP server (headscale v0.25.1 refuses to boot with an empty DERPMap)"
    assert "derp:\n  server:\n    enabled: true" in text, "embedded DERP server must be enabled"
    assert "stun_listen_addr:" in text, "embedded DERP requires derp.server.stun_listen_addr"
    assert _re.search(r'stun_listen_addr: "127\.0\.0\.1:\d{4,5}"', text), (
        "embedded DERP STUN must bind loopback with a real port"
    )
    assert f"private_key_path: {CONTAINER_STATE_DIR}/derp_server_private.key" in text, (
        "embedded DERP private key must be container-mapped"
    )
    assert "automatically_add_embedded_derp_region: true" in text, (
        "embedded DERP region must be auto-added (non-empty DERPMap)"
    )
