"""Accepted TASK-9826 T1–T5 terminal-reader supplements.

Real retained consumers, production SQLite writers and idle TaskQueue. Expected
new rows are literals authored from pristine DDL; timestamps alone are bound to
the action interval. Existing keepers remain unchanged.
"""
from __future__ import annotations

import copy
import json
import subprocess
import sys
from collections import Counter
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

import pytest

from runtime.config import Settings
from runtime.daemon.queue import TaskQueue
from runtime.infrastructure.database import Database
from runtime.models import BlockKind, TaskRecord, TaskStatus
from runtime.orchestrator import run_step
from runtime.orchestrator._paths import OrgPaths
from runtime.orchestrator.orchestrator import Orchestrator
from runtime.orchestrator.teams import TeamsRegistry
from runtime.runtime import RuntimeDir

CHAIN1 = ('{"step_index": 1, "first_leg_expect_verdict": null, "legs": [{"agent": "code_reviewer", '
 '"prompt": "review brief", "expect_verdict": "APPROVE", "attachments": null}, {"agent": '
 '"qa_engineer", "prompt": "qa brief", "expect_verdict": "PASS", "attachments": null}], '
 '"step_audit_id": 91}')
CHAIN2 = ('{"step_index": 2, "first_leg_expect_verdict": null, "legs": [{"agent": "code_reviewer", '
 '"prompt": "review brief", "expect_verdict": "APPROVE", "attachments": null}, {"agent": '
 '"qa_engineer", "prompt": "qa brief", "expect_verdict": "PASS", "attachments": null}], '
 '"step_audit_id": 91}')
CHAIN_FINAL = ('{"step_index": 1, "first_leg_expect_verdict": null, "legs": [{"agent": "qa_engineer", '
 '"prompt": "qa brief", "expect_verdict": "PASS", "attachments": null}], "step_audit_id": 91}')
FANOUT = ('{"children_ids": ["TASK-P", "TASK-LIVE"], "children_details": [], "width": 2, "manager_agent": '
 '"engineering_head", "join_summary": "combine", "status": "spawned"}')
REPORT = {'task_id': 'TASK-R',
 'agent': 'code_reviewer',
 'status': 'completed',
 'confidence': 90,
 'output_summary': 'exact summary\nsecond line',
 'verdict': 'APPROVE',
 'decision': None,
 'manager_self_evaluation': None,
 'risks_flagged': ['risk one', 'risk two'],
 'dependencies': [],
 'suggested_reviewer_focus': [],
 'output_dir': 'output/TASK-R',
 'waiting_on_job_ids': ['JOB-1'],
 'local_ci': None}
NEXT_TASK = {'id': 'TASK-001',
 'status': 'pending',
 'assigned_agent': 'qa_engineer',
 'team': 'engineering',
 'brief': 'qa brief\n'
          '---\n'
          '## Prior leg context (auto-generated by orchestrator)\n'
          '\n'
          'Prior leg:    TASK-R  (agent: code_reviewer)\n'
          'Status:       completed\n'
          'Verdict:      APPROVE\n'
          'Confidence:   90\n'
          'Summary:\n'
          '  exact summary\n'
          '  second line\n'
          '\n'
          'Output dir: output/TASK-R\n'
          '---',
 'revision_count': 0,
 'created_at': '$NEXT_CREATED_AT',
 'updated_at': '$NEXT_UPDATED_AT',
 'completed_at': None,
 'parent_task_id': 'TASK-P',
 'revisit_of_task_id': None,
 'dispatched_from_thread_id': None,
 'block_kind': None,
 'blocked_on_job_ids': None,
 'note': None,
 'orchestration_step_count': 0,
 'session_timeout_seconds': 180,
 'task_type': 'subtask',
 'active_fanout': None,
 'active_chain': None,
 'current_session_id': None,
 'zombie_flagged_at': None,
 'executor_pid': None,
 'last_heartbeat': None,
 'cancelled_at': None,
 'final_output_dir': None,
 'final_output_summary': None}
TASK_DEFAULTS = {'id': '$ID',
 'status': 'pending',
 'assigned_agent': None,
 'team': 'engineering',
 'brief': '$BRIEF',
 'revision_count': 0,
 'created_at': '$NEXT_CREATED_AT',
 'updated_at': '$NEXT_UPDATED_AT',
 'completed_at': None,
 'parent_task_id': None,
 'revisit_of_task_id': None,
 'dispatched_from_thread_id': None,
 'block_kind': None,
 'blocked_on_job_ids': None,
 'note': None,
 'orchestration_step_count': 0,
 'session_timeout_seconds': None,
 'task_type': 'task',
 'active_fanout': None,
 'active_chain': None,
 'current_session_id': None,
 'zombie_flagged_at': None,
 'executor_pid': None,
 'last_heartbeat': None,
 'cancelled_at': None,
 'final_output_dir': None,
 'final_output_summary': None}
VERDICT_ROWS = [{'verdict': 'APPROVE',
  'success': True,
  'expected_payload_raw': '{"verdict": "APPROVE", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': 'APPROVE',
  'success': False,
  'expected_payload_raw': '{"verdict": "APPROVE", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': 'PASS',
  'success': True,
  'expected_payload_raw': '{"verdict": "PASS", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': 'PASS',
  'success': False,
  'expected_payload_raw': '{"verdict": "PASS", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': 'REQUEST_CHANGES',
  'success': True,
  'expected_payload_raw': '{"verdict": "REQUEST_CHANGES", "feedback": "literal feedback\\nsecond '
                          'line", "reviewed_agent": "qa_engineer"}'},
 {'verdict': 'REQUEST_CHANGES',
  'success': False,
  'expected_payload_raw': '{"verdict": "REQUEST_CHANGES", "feedback": "literal feedback\\nsecond '
                          'line", "reviewed_agent": "qa_engineer"}'},
 {'verdict': 'unknown-value',
  'success': True,
  'expected_payload_raw': '{"verdict": "unknown-value", "feedback": "literal feedback\\nsecond '
                          'line", "reviewed_agent": "qa_engineer"}'},
 {'verdict': 'unknown-value',
  'success': False,
  'expected_payload_raw': '{"verdict": "unknown-value", "feedback": "literal feedback\\nsecond '
                          'line", "reviewed_agent": "qa_engineer"}'},
 {'verdict': '',
  'success': True,
  'expected_payload_raw': '{"verdict": "", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': '',
  'success': False,
  'expected_payload_raw': '{"verdict": "", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': '   ',
  'success': True,
  'expected_payload_raw': '{"verdict": "   ", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'verdict': '   ',
  'success': False,
  'expected_payload_raw': '{"verdict": "   ", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'report_present': False,
  'verdict': None,
  'success': True,
  'expected_payload_raw': '{"verdict": "approved", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'report_present': False,
  'verdict': None,
  'success': False,
  'expected_payload_raw': '{"verdict": "rejected", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'report_present': True,
  'verdict': None,
  'success': True,
  'expected_payload_raw': '{"verdict": "approved", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'},
 {'report_present': True,
  'verdict': None,
  'success': False,
  'expected_payload_raw': '{"verdict": "rejected", "feedback": "literal feedback\\nsecond line", '
                          '"reviewed_agent": "qa_engineer"}'}]

FEEDBACK = "literal feedback\nsecond line"
FAIL_NOTE = (
    "carrier chain leg TASK-R failed; causal_leaf_id=TASK-R; causal_status=failed; "
    "causal_verdict=(none); causal_revisit_of_task_id=(none); "
    "causal_reason=review tool unavailable"
)


@contextmanager
def make_env(tmp_path):
    rt = RuntimeDir.init(tmp_path / "runtime")
    paths = OrgPaths(root=rt.orgs_dir / "test-org")
    paths.teams_config_path.parent.mkdir(parents=True, exist_ok=True)
    paths.teams_config_path.write_text(
        "teams:\n  engineering:\n    manager: engineering_head\n"
        "    workers: [dev_agent, code_reviewer, qa_engineer]\n"
    )
    db = Database(paths.db_path)
    queue = TaskQueue()
    orch = Orchestrator(db=db, settings=Settings(), paths=paths,
                        slug="test-org", teams=TeamsRegistry.load(paths.root))
    orch.attach_queue(queue)
    try:
        yield orch
    finally:
        # No workers, loops or sessions were started. Drain only this fixture's
        # pending entries, through the production tracked dequeue boundary.
        assert not queue._worker_tasks
        while not queue._queue.empty():
            queue._queue.get_nowait()
            queue._queue.task_done()
        assert not queue._pending_counts
        assert not queue._admission_reservations
        db.close()


@pytest.fixture
def env(tmp_path):
    with make_env(tmp_path) as orch:
        yield orch


def snapshot(orch):
    """All columns of every table, including allocator sequences and raw JSON."""
    db = orch._db
    names = [r[0] for r in db.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    )]
    return {n: [dict(r) for r in db.execute(f'SELECT * FROM "{n}" ORDER BY rowid')]
            for n in names}


def queue_items(orch):
    q = orch._queue
    assert not q._worker_tasks
    assert not q._admission_reservations
    items = list(q._queue._queue)
    assert q._pending_counts == Counter((s, t) for s, t, _ in items)
    return items


def task(orch, task_id, **kwargs):
    start = datetime.now(timezone.utc)
    orch._db.insert_task(TaskRecord(id=task_id, brief=task_id, **kwargs))
    raw = dict(orch._db.execute("SELECT * FROM tasks WHERE id=?", (task_id,)).fetchone())
    expected = dict(TASK_DEFAULTS, id=task_id, brief=task_id)
    expected.update({k: getattr(v, "value", v) for k, v in kwargs.items()})
    for key in ("created_at", "updated_at"):
        expected[key] = time_binding(raw[key], start, datetime.now(timezone.utc))
    assert raw == expected


def result(orch, *, task_id="TASK-R", agent="code_reviewer",
           session="sess-current", status="completed", verdict="APPROVE"):
    start = datetime.now(timezone.utc)
    next_id = orch._db.execute("SELECT COALESCE(MAX(id),0)+1 FROM task_results").fetchone()[0]
    orch._db.insert_task_result(
        task_id=task_id, agent=agent, session_id=session, status=status,
        verdict=verdict, confidence_score=90,
        output_summary="exact summary\nsecond line", output_dir="output/TASK-R",
        risks_flagged=["risk one", "risk two"], waiting_on_job_ids=["JOB-1"],
    )
    raw = dict(orch._db.execute("SELECT * FROM task_results WHERE id=?", (next_id,)).fetchone())
    assert raw == {
        "id": next_id, "task_id": task_id, "agent": agent, "session_id": session,
        "status": status, "output_summary": "exact summary\nsecond line",
        "decision_json": None, "confidence_score": 90, "learnings": None,
        "risks_flagged": '["risk one", "risk two"]', "duration_seconds": None,
        "token_count": None, "estimated_cost": None, "output_dir": "output/TASK-R",
        "created_at": time_binding(raw["created_at"], start, datetime.now(timezone.utc)),
        "waiting_on_job_ids": '["JOB-1"]', "verdict": verdict, "local_ci": None,
    }


def seed_chain(orch, *, child_status=TaskStatus.COMPLETED,
               agent="code_reviewer", session="sess-current",
               parent_type="task", grandparent=None, final=False):
    task(orch, "TASK-P", assigned_agent=("dev_agent" if parent_type == "subtask"
                                        else "engineering_head"),
         parent_task_id=grandparent, task_type=parent_type,
         session_timeout_seconds=180)
    orch._db.update_task("TASK-P", status=TaskStatus.IN_PROGRESS,
                        block_kind=BlockKind.DELEGATED, note="waiting")
    orch._db.update_task_active_chain("TASK-P", CHAIN_FINAL if final else CHAIN1)
    task(orch, "TASK-R", parent_task_id="TASK-P", assigned_agent=agent,
         task_type="subtask")
    orch._db.update_task("TASK-R", status=child_status, current_session_id=session)


def time_binding(raw, start, end):
    assert isinstance(raw, str)
    parsed = datetime.fromisoformat(raw)
    assert start <= parsed <= end
    return raw


def expect_delta(orch, before, start, *, updates=None, new_task=False,
                 audit=None, queue=()):
    """Explicit changes applied to pristine rows; no field is erased."""
    end = datetime.now(timezone.utc)
    actual = snapshot(orch)
    expected = copy.deepcopy(before)
    for tid, changes in (updates or {}).items():
        row = next(r for r in expected["tasks"] if r["id"] == tid)
        observed = next(r for r in actual["tasks"] if r["id"] == tid)
        for key, value in changes.items():
            if value != "$TIME":
                assert observed[key] == value, (tid, key, observed[key], value)
            row[key] = time_binding(observed[key], start, end) if value == "$TIME" else value
    if new_task:
        observed = next(r for r in actual["tasks"] if r["id"] == "TASK-001")
        row = copy.deepcopy(NEXT_TASK)
        for key in ("created_at", "updated_at"):
            row[key] = time_binding(observed[key], start, end)
        expected["tasks"].append(row)
    if audit:
        prior_id = max((r["id"] for r in before["audit_log"]), default=0)
        row = {"id": prior_id + 1, "task_id": audit[0], "agent": audit[1],
               "action": audit[2], "payload": audit[3],
               "timestamp": time_binding(actual["audit_log"][-1]["timestamp"], start, end)}
        expected["audit_log"].append(row)
        seq = next((r for r in expected["sqlite_sequence"] if r["name"] == "audit_log"), None)
        if seq is None:
            expected["sqlite_sequence"].append({"name": "audit_log", "seq": prior_id + 1})
        else:
            seq["seq"] = prior_id + 1
    assert actual == expected
    assert queue_items(orch) == [("test-org", tid, None) for tid in queue]


def advance(orch, before, start):
    expect_delta(orch, before, start, updates={"TASK-P": {"active_chain": CHAIN2}},
                 new_task=True, audit=("TASK-P", "orchestrator", "chain_auto_advance",
                 '{"leg_index": 2, "spawned_child_id": "TASK-001", "triggering_child_id": "TASK-R", '
                 '"triggering_verdict": "APPROVE", "chain_origin_step_audit_id": 91}'),
                 queue=("TASK-001",))
    stable = snapshot(orch)
    run_step._enqueue_parent_if_waiting(orch, "TASK-R")
    assert snapshot(orch) == stable
    assert queue_items(orch) == [("test-org", "TASK-001", None)]


def wake(orch, before, start):
    expect_delta(orch, before, start,
                 updates={"TASK-P": {"active_chain": None, "updated_at": "$TIME"}},
                 queue=("TASK-P",))
    stable = snapshot(orch)
    run_step._enqueue_parent_if_waiting(orch, "TASK-R")
    assert snapshot(orch) == stable
    assert queue_items(orch) == [("test-org", "TASK-P", None)]


def audit_setup(orch, agent="qa_engineer", parent="TASK-P"):
    task(orch, "TASK-P", assigned_agent="engineering_head")
    task(orch, "TASK-R", assigned_agent=agent, parent_task_id=parent, task_type="subtask")
    orch._db.update_task("TASK-R", status=TaskStatus.COMPLETED, note=FEEDBACK)
    orch._db.insert_audit_log("TASK-R", "orchestrator", "seed", {"literal": "prior"})


@pytest.mark.parametrize("verdict,success", [(v, s) for v in
    ["APPROVE", "PASS", "REQUEST_CHANGES", "unknown-value", "", "   "] for s in [True, False]])
def test_terminal_reader_verdict_audit_literal(env, verdict, success):
    """T1.1: exact explicit bytes, raw feedback/order and zero residue."""
    audit_setup(env)
    result(env, agent="qa_engineer", verdict=verdict)
    before = snapshot(env)
    assert run_step._verdict_for_delegated(env, "TASK-R", success=success) == verdict
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._log_verdict_if_delegated(env, "TASK-R", success=success)
    payload = next(r["expected_payload_raw"] for r in VERDICT_ROWS
                   if r.get("verdict") == verdict and r["success"] == success)
    expect_delta(env, before, start, audit=("TASK-R", "engineering_head", "review_verdict", payload))


@pytest.mark.parametrize("present,success", [(p, s) for p in [False, True] for s in [True, False]])
def test_terminal_reader_verdict_fallback_audit(env, present, success):
    """T1.2: NULL and absent differ from explicit blank."""
    audit_setup(env)
    if present:
        result(env, agent="qa_engineer", verdict=None)
    before = snapshot(env)
    start = datetime.now(timezone.utc)
    run_step._log_verdict_if_delegated(env, "TASK-R", success=success)
    payload = next(r["expected_payload_raw"] for r in VERDICT_ROWS
                   if r.get("report_present") == present and r["success"] == success)
    expect_delta(env, before, start, audit=("TASK-R", "engineering_head", "review_verdict", payload))


@pytest.mark.parametrize("case", ["eligible", "root", "manager", "orchestrator",
                                  "unknown", "null-agent", "empty-agent", "missing"])
def test_terminal_reader_facade_verdict_lookup(env, monkeypatch, case):
    """T1.3/T5.2: retained writer resolves the facade; suppression never calls it."""
    agent = {"manager": "engineering_head", "null-agent": None,
             "empty-agent": "", "orchestrator": "orchestrator", "unknown": "unknown"}.get(case, "qa_engineer")
    audit_setup(env, agent=agent, parent=None if case == "root" else "TASK-P")
    def witness(*args, **kwargs):
        assert case == "eligible", "suppressed caller reached verdict reader"
        return "old helper witness"
    monkeypatch.setattr(run_step, "_verdict_for_delegated", witness)
    before = snapshot(env)
    start = datetime.now(timezone.utc)
    run_step._log_verdict_if_delegated(env, "missing" if case == "missing" else "TASK-R", success=True)
    audit = ("TASK-R", "engineering_head", "review_verdict",
             '{"verdict": "old helper witness", "feedback": "literal feedback\\nsecond line", "reviewed_agent": "qa_engineer"}') if case == "eligible" else None
    expect_delta(env, before, start, audit=audit)


def seed_fanout(orch, *, variant="member", live=TaskStatus.IN_PROGRESS):
    task(orch, "TASK-G", assigned_agent="engineering_head")
    orch._db.update_task("TASK-G", status=TaskStatus.IN_PROGRESS,
                        block_kind=BlockKind.DELEGATED, note="outer waiting")
    raw = {"no-fanout": None, "malformed": "not-json{{[", "empty": "{}",
           "not-member": FANOUT.replace('"TASK-P"', '"TASK-OTHER"')}.get(variant, FANOUT)
    orch._db.update_task_active_fanout("TASK-G", raw)
    task(orch, "TASK-LIVE", parent_task_id="TASK-G", assigned_agent="qa_engineer")
    orch._db.update_task("TASK-LIVE", status=live)


@pytest.mark.parametrize("case", ["root", "missing-grandparent", "manager", "carrier",
                                  "no-fanout", "not-member", "malformed", "empty"])
def test_terminal_reader_failed_parent_classification(env, monkeypatch, tmp_path, case):
    """T2.1/T5.2: same membership does not make a decision owner passive."""
    seed_fanout(env, variant=case)
    grandparent = None if case == "root" else "missing" if case == "missing-grandparent" else "TASK-G"
    seed_chain(env, child_status=TaskStatus.FAILED, grandparent=grandparent,
               parent_type="task" if case == "manager" else "subtask")
    env._db.update_task("TASK-R", note="review tool unavailable")
    result(env, status="blocked", verdict=None)
    before = snapshot(env)
    parent = env._db.get_task("TASK-P")
    assert run_step._is_carrier(env, parent) is (case == "carrier")
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    if case == "carrier":
        expect_delta(env, before, start, updates={"TASK-P": {
            "active_chain": None, "active_fanout": None, "status": "failed",
            "block_kind": None, "note": FAIL_NOTE, "completed_at": "$TIME", "updated_at": "$TIME"}},
            audit=("TASK-P", "engineering_head", "review_verdict", json.dumps({
                "verdict": "rejected", "feedback": FAIL_NOTE, "reviewed_agent": "dev_agent"})))
        # A separate owned pristine DB/queue supplies the old-path control.
        with make_env(tmp_path / "facade-control") as controlled:
            seed_fanout(controlled, variant=case)
            seed_chain(controlled, child_status=TaskStatus.FAILED,
                       grandparent="TASK-G", parent_type="subtask")
            controlled._db.update_task("TASK-R", note="review tool unavailable")
            result(controlled, status="blocked", verdict=None)
            with monkeypatch.context() as patch:
                patch.setattr(run_step, "_is_carrier", lambda *a: False)
                clean = snapshot(controlled)
                start = datetime.now(timezone.utc)
                run_step._enqueue_parent_if_waiting(controlled, "TASK-R")
                wake(controlled, clean, start)
    else:
        wake(env, before, start)


@pytest.mark.parametrize("parent_type,live", [(p, s) for p in ["task", "subtask"]
                                             for s in [TaskStatus.IN_PROGRESS, TaskStatus.COMPLETED]])
def test_terminal_reader_final_leg_ownership(env, parent_type, live):
    """T2.2: final-leg closure retains the outer barrier and all leaf evidence."""
    seed_fanout(env, live=live)
    seed_chain(env, child_status=TaskStatus.IN_PROGRESS, agent="qa_engineer",
               grandparent="TASK-G", parent_type=parent_type, final=True)
    result(env, agent="qa_engineer", verdict="PASS")
    before = snapshot(env)
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    if parent_type == "task":
        wake(env, before, start)
    else:
        expect_delta(env, before, start, updates={"TASK-P": {
            "active_chain": None, "status": "completed", "block_kind": None,
            "note": "carrier chain complete", "final_output_dir": None,
            "completed_at": "$TIME", "updated_at": "$TIME"}},
            audit=("TASK-P", "engineering_head", "review_verdict",
                   '{"verdict": "approved", "feedback": "carrier chain complete", "reviewed_agent": "dev_agent"}'),
            queue=("TASK-G",) if live == TaskStatus.COMPLETED else ())
        stable = snapshot(env)
        run_step._enqueue_parent_if_waiting(env, "TASK-R")
        assert snapshot(env) == stable
        assert queue_items(env) == ([("test-org", "TASK-G", None)] if live == TaskStatus.COMPLETED else [])


@pytest.mark.parametrize("agent,session", [(a, s) for a in [None, "", "code_reviewer"]
                                         for s in [None, "", "sess-current"]] + [("$NONE", None)])
def test_terminal_reader_partial_fingerprint_chain(env, agent, session):
    """T3.1: genuine absence falls back; complete fingerprints remain exact."""
    if agent == "$NONE":
        before = snapshot(env)
        assert run_step._child_has_modern_fingerprint(None) is False
        assert run_step._child_landed_terminal_report(env, None) is None
        assert run_step._child_has_landed_terminal_result(env, None) is False
        run_step._enqueue_parent_if_waiting(env, "missing")
        assert snapshot(env) == before
        assert queue_items(env) == []
        return
    seed_chain(env, agent=agent, session=session)
    result(env)
    before = snapshot(env)
    modern = agent == "code_reviewer" and session == "sess-current"
    assert run_step._child_has_modern_fingerprint(env._db.get_task("TASK-R")) is modern
    report = run_step._child_landed_terminal_report(env, env._db.get_task("TASK-R"))
    assert (report is not None) is modern
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    advance(env, before, start)


@pytest.mark.parametrize("case", ["wrong-task", "no-row"])
def test_terminal_reader_absent_scoped_evidence_residue(env, case):
    """T3.2: a modern completed child cannot consume task-wide evidence."""
    seed_chain(env)
    if case == "wrong-task":
        task(env, "TASK-OTHER")
        result(env, task_id="TASK-OTHER")
    before = snapshot(env)
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    wake(env, before, start)


def test_terminal_reader_full_report_consumer(env, monkeypatch):
    """T4.1/T5.2: complete projection and exact shipping brief during status lag."""
    seed_chain(env, child_status=TaskStatus.IN_PROGRESS)
    result(env)
    before = snapshot(env)
    child = env._db.get_task("TASK-R")
    returned = run_step._child_landed_terminal_report(env, child)
    assert returned is not None
    assert returned.model_dump() == REPORT
    assert run_step._child_has_landed_terminal_result(env, child) is True
    assert snapshot(env) == before
    with monkeypatch.context() as patch:
        patch.setattr(run_step, "_child_landed_terminal_report", lambda *a: None)
        assert run_step._child_has_landed_terminal_result(env, child) is False
        run_step._enqueue_parent_if_waiting(env, "TASK-R")
        assert snapshot(env) == before
        assert queue_items(env) == []
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    advance(env, before, start)


def test_terminal_reader_latest_exact_status(env):
    """T4.2: the newest SAME triple blocks an older passing exact result."""
    seed_chain(env)
    result(env)
    result(env, status="blocked")
    before = snapshot(env)
    assert run_step._child_landed_terminal_report(env, env._db.get_task("TASK-R")) is None
    assert run_step._child_has_landed_terminal_result(env, env._db.get_task("TASK-R")) is False
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    wake(env, before, start)


def corrupt_exact(orch, field, value):
    assert field in {"status", "risks_flagged", "waiting_on_job_ids", "decision_json", "confidence_score", "local_ci"}
    orch._db.execute(f"UPDATE task_results SET {field}=? WHERE id=1", (value,))
    orch._db._conn.commit()


def polluted(orch, field, value, *, legacy=False):
    seed_chain(orch, agent=None if legacy else "code_reviewer",
               session=None if legacy else "sess-current")
    result(orch)
    corrupt_exact(orch, field, value)
    if not legacy:
        result(orch, agent="wrong-agent", session="wrong-session")


@pytest.mark.parametrize("status", ["blocked", "in_progress", "failed", "mystery", ""])
def test_terminal_reader_status_decode_boundary(env, status):
    """T4.3: free status strings fail closed; the retained blank coercion accepts."""
    polluted(env, "status", status)
    before = snapshot(env)
    report = run_step._child_landed_terminal_report(env, env._db.get_task("TASK-R"))
    assert (report is not None) is (status == "")
    if status == "":
        assert report is not None
        assert report.model_dump() == REPORT
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    (advance if status == "" else wake)(env, before, start)


@pytest.mark.parametrize("field,value", [("risks_flagged", "not-json{{["),
    ("waiting_on_job_ids", "not-json{{["), ("decision_json", "not-json{{["),
    ("risks_flagged", "1"), ("risks_flagged", "{}"), ("risks_flagged", "[1]"),
    ("confidence_score", 101)], ids=["invalid-risks-json", "invalid-waiting-json",
    "invalid-decision-json", "risks-scalar", "risks-dict", "risks-non-string-list", "confidence101"])
def test_terminal_reader_malformed_exact_report_residue(env, field, value):
    """T4.3: exact projection errors are absence, with corrupt raw bytes retained."""
    polluted(env, field, value)
    before = snapshot(env)
    assert run_step._child_landed_terminal_report(env, env._db.get_task("TASK-R")) is None
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    wake(env, before, start)


def test_terminal_reader_local_ci_degradation_consumer(env):
    """T4.3: malformed optional local CI does not discard a valid terminal report."""
    polluted(env, "local_ci", "not-json{{[")
    before = snapshot(env)
    returned = run_step._child_landed_terminal_report(env, env._db.get_task("TASK-R"))
    assert returned is not None
    assert returned.model_dump() == REPORT
    assert snapshot(env) == before
    start = datetime.now(timezone.utc)
    run_step._enqueue_parent_if_waiting(env, "TASK-R")
    advance(env, before, start)


@pytest.mark.parametrize("legacy", [False, True], ids=["modern-exact-json-error", "legacy-unscoped-json-error"])
def test_terminal_reader_legacy_decode_error_residue(env, legacy):
    """T4.4: genuine legacy unscoped decoder errors propagate without writes."""
    polluted(env, "risks_flagged", "not-json{{[", legacy=legacy)
    before = snapshot(env)
    start = datetime.now(timezone.utc)
    if legacy:
        with pytest.raises(json.JSONDecodeError) as error:
            run_step._enqueue_parent_if_waiting(env, "TASK-R")
        assert str(error.value) == "Expecting value: line 1 column 1 (char 0)"
        expect_delta(env, before, start)
    else:
        run_step._enqueue_parent_if_waiting(env, "TASK-R")
        wake(env, before, start)


@pytest.mark.parametrize("order", ["facade-first", "readers-first"])
def test_terminal_reader_fresh_import_contract(order):
    """T5.1: each import order exposes the same unique definitions, without cycles."""
    root = Path(__file__).resolve().parents[1]
    script = '''
import ast, importlib, inspect, json, pathlib, sys
assert not any(n.startswith('runtime.') for n in sys.modules)
names = ['runtime.orchestrator.run_step', 'runtime.orchestrator.task_terminal_readers']
if sys.argv[1] == 'readers-first': names.reverse()
for name in names: importlib.import_module(name)
facade = importlib.import_module('runtime.orchestrator.run_step')
readers = importlib.import_module('runtime.orchestrator.task_terminal_readers')
selected = ['_verdict_for_delegated', '_is_carrier', '_child_has_modern_fingerprint', '_child_landed_terminal_report']
assert pathlib.Path(facade.__file__).resolve() == pathlib.Path.cwd() / 'runtime/orchestrator/run_step.py'
assert pathlib.Path(readers.__file__).resolve() == pathlib.Path.cwd() / 'runtime/orchestrator/task_terminal_readers.py'
assert sorted(dir(facade)) == ['BlockKind', 'Callable', 'Committed', 'InvalidLineage', 'LostClaim', 'ModuleType', 'NamedTuple', 'Path', 'PendingRetry', 'RetryClaim', 'SpawnOutcome', 'TERMINAL_STATES', 'TYPE_CHECKING', 'TaskStatus', 'TerminalWorktreeReclaimOutcome', '_FAILURE_ROUND_BOUND', '_NO_AUTHENTICATED_REPORT', '_NoAuthenticatedReport', '_PARKED_CARRIER_STATUSES', '_REVISIT_DISCIPLINE_LINES', '_SLICE_RETRY_CEILING', '_TERMINAL_WORKTREE_OUTPUT_LIMIT', '_TERMINAL_WORKTREE_SCANNER_LOCK', '_TERMINAL_WORKTREE_SCANNER_MODULE', '_TERMINAL_WORKTREE_SCANNER_MODULE_NAME', '_TERMINAL_WORKTREE_SCANNER_PATH', '_TERMINAL_WORKTREE_STATUSES', '_TERMINAL_WORKTREE_TIMEOUT_SECONDS', '_V2DecisionDispatchOutcome', '_V2_DECISION_DISPATCH_ADMITTED', '_V2_DECISION_DISPATCH_ORDINARY', '_V2_DECISION_DISPATCH_SKIP', '__annotations__', '__builtins__', '__cached__', '__conditional_annotations__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_advance_chain_for_completed_child', '_append_followup_system_and_reinvoke', '_auto_revisit_header', '_blocked_jobs_resume_header_if_applicable', '_build_agent_prompt', '_build_prior_steps_from_db', '_carrier_complete_on_chain_complete', '_carrier_fail_immediate', '_carrier_fail_on_verdict_mismatch', '_check_retry_link_required', '_child_has_landed_terminal_result', '_child_has_modern_fingerprint', '_child_landed_terminal_report', '_complete', '_consume_accepted_completion_recovery', '_consume_completion_report', '_consume_completion_report_body', '_current_unresolved_failed_leaves', '_default_agent_for_root', '_enqueue_parent_if_waiting', '_enqueue_task_generation_aware', '_escalate_continued_turn_violation', '_fail', '_fail_terminal_tail', '_fanout_join_header_if_applicable', '_feedback_and_reenqueue', '_format_slice_retry_exhausted_reason', '_handoff_consumed_recovery_terminal_effects', '_inject_fanout_join_context', '_is_already_terminal', '_is_carrier', '_is_continued_turn_decision', '_is_reviewer_omission_error', '_is_slice_retry_exhausted', '_kill_jobs_for_terminating_task', '_legs_out_of_scope', '_list_candidate_agents', '_load_terminal_worktree_scanner', '_log_verdict_if_delegated', '_maybe_post_thread_escalation', '_maybe_post_thread_followup', '_maybe_resume_blocked_task', '_meaningful_stderr', '_payload_dict', '_prepare_attachment_params', '_prepare_workspace_cleanup_reclamation_context', '_reclaim_terminal_task_worktree', '_reject_retry_link_decision', '_reject_reviewer_omission', '_request_pending_v2_publication', '_resolve_completion_result_row_id', '_resolved_escalation_header_if_applicable', '_reviewer_agents_for', '_reviewer_omitted_expectation_error', '_revisit_header_if_applicable', '_run_terminal_worktree_command', '_session_failed_note', '_spawn_fanout_children', '_spend_envelope_as_consumed', '_spend_envelope_as_violation', '_summarize_recent_chain', '_task_matches_authority_v2_refusal_failure', '_terminal_worktree_path_has_symlink', '_terminal_worktree_process_reference', '_terminal_worktree_remaining', '_v2_decision_dispatch_gate', '_v2_report_binds', '_validate_decision_attachments', '_validate_delegate', '_validate_one_leg', '_verdict_for_delegated', '_workspace_cleanup_remainder', '_workspace_cleanup_remainder_fact', 'annotations', 'datetime', 'importlib', 'is_root', 'json', 'load_org_config', 'logger', 'logging', 'os', 'run_step_impl', 'stat', 'subprocess', 'sys', 'threading', 'time', 'timedelta', 'timezone']
for name in selected:
    assert getattr(facade, name) is getattr(readers, name), name
    assert getattr(facade, name).__module__ == readers.__name__, name
    assert getattr(facade, name).__defaults__ is None
    definitions = [(str(p), n.name) for p in pathlib.Path('runtime').rglob('*.py')
                   for n in ast.walk(ast.parse(p.read_bytes()))
                   if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == name]
    assert len(definitions) == 1, (name, definitions)
assert facade._child_has_landed_terminal_result.__module__ == facade.__name__
assert type(facade._NO_AUTHENTICATED_REPORT) is facade._NoAuthenticatedReport
assert not hasattr(readers, '_NO_AUTHENTICATED_REPORT')
assert not hasattr(readers, 'TaskStatus')
print(json.dumps({'order':sys.argv[1], 'selected':selected}))
'''
    completed = subprocess.run([sys.executable, "-c", script, order], cwd=root,
                               capture_output=True, text=True, timeout=30)
    assert completed.returncode == 0, completed.stdout + completed.stderr
    assert json.loads(completed.stdout)["order"] == order
