import AppKit
import HappyRanchSupervisor

/// Application delegate — owns the daemon supervisor and app-level state.
@MainActor
final class AppDelegate: NSObject, NSApplicationDelegate, ObservableObject {

    let supervisor = DaemonSupervisor()
    let diagnostics = DiagnosticsCollector(homeDir: daemonHome())

    /// Transport for constructing daemon URLs. Only LocalLoopbackTransport is wired.
    let localTransport: RuntimeTransport = LocalLoopbackTransport()

    /// Injected process controller — wraps Foundation.Process in production,
    /// replaced with a FakeProcessController in tests.
    var processController: ProcessControlling = RealProcessController()

    /// The handle for the currently active managed daemon process.
    /// Set on each launch; used to guard stale exit callbacks by identity.
    /// Internal to allow tests to inject a handle for termination-path coverage.
    var currentHandle: (any ProcessHandle)?

    @Published var webViewURL: String?
    @Published var stateText: String = DaemonState.notConfigured.description
    @Published var showDiagnostics = false

    // MARK: - A2 Remote connection state

    /// Persisted role preference (nil = first launch / undetermined).
    /// Stored in UserDefaults under `connectionRolePreference`.
    /// When the user explicitly picks HOME or CLIENT on first launch,
    /// this preference takes priority over supervisor-state heuristics.
    @Published var connectionRolePreference: ConnectionRolePreference? {
        didSet {
            if let pref = connectionRolePreference {
                UserDefaults.standard.set(pref.rawValue, forKey: "connectionRolePreference")
            } else {
                UserDefaults.standard.removeObject(forKey: "connectionRolePreference")
            }
        }
    }

    /// The connection role of this machine (HOME vs CLIENT).
    /// Consults the explicit ``connectionRolePreference`` first;
    /// falls back to ``DaemonSupervisor/state`` when undetermined.
    var connectionRole: ConnectionRole {
        ConnectionRole.detect(supervisor: supervisor, preference: connectionRolePreference)
    }

    /// Shared pairing store used by both the HomeConnector and the UI.
    let pairingStore = RealPairingStore()

    /// Tailscale status provider (injectable for tests; production = real).
    var tailscaleProvider: TailscaleStatusProviding = TailscaleStatusProvider()

    /// The home connector (only active in HOME role).
    var homeConnector: HomeConnector?

    /// The client loopback bridge (only active in CLIENT role).
    var clientBridge: ClientBridge?

    /// Connection state manager for the remote-connection surface.
    let connectionStateManager = ConnectionStateManager()

    /// The chosen port for the home connector to listen on.
    @Published var homeConnectorPort: UInt16 = 8443

    /// The one-time pairing code generated by the home side.
    @Published var pairingCode: String?

    /// The home machine's tailnet IP (for display to the client user).
    @Published var tailnetSelfIP: String?

    /// Connection state for UI binding.
    @Published var connectionState: ConnectionState = .tailnetNotDetected

    // --- CLIENT-side input fields ---
    @Published var clientHomeHost: String = ""
    @Published var clientHomePort: String = "8443"
    @Published var clientPairingCode: String = ""
    @Published var clientConnectError: String?
    @Published var isConnecting: Bool = false

    /// Derived state published for menu-command enable/disable bindings.
    @Published var canStart = false
    @Published var canStop = false
    @Published var canRestart = false

    /// When true, the termination-completion path will start the daemon
    /// after it settles to .stopped.  Set by restartDaemon(), cleared
    /// after the follow-on start is issued.
    private var pendingRestart = false

    func applicationDidFinishLaunching(_ notification: Notification) {
        // Foreground the app as a regular Dock-present application so a bare
        // `swift run` executable gets a visible window without requiring a .app bundle.
        NSApplication.shared.setActivationPolicy(.regular)
        NSApplication.shared.activate(ignoringOtherApps: true)

        // Load persisted role preference from UserDefaults
        if let raw = UserDefaults.standard.string(forKey: "connectionRolePreference"),
           let pref = ConnectionRolePreference(rawValue: raw) {
            connectionRolePreference = pref
        }

        let home = daemonHome()
        // Only configure the supervisor when the user intent is HOME or undetermined.
        // For CLIENT machines, skip supervisor.configure entirely — the role will
        // be derived from the explicit preference (ConnectionRole.detect returns
        // .client before the preference is consulted, and the preference takes priority).
        if connectionRolePreference != .client {
            supervisor.configure(homeDir: home)
        }
        refreshDerivedState()

        // Check for existing daemon
        discoverExistingDaemon()
    }

    func applicationWillTerminate(_ notification: Notification) {
        // Terminate the managed daemon if it's still alive.
        // External daemons are NEVER terminated on quit.
        if supervisor.isManagedBySelf,
           supervisor.state == .running || supervisor.state == .starting || supervisor.state == .unhealthy {
            terminateManagedProcess()
        }
    }

    // MARK: - Daemon home

    nonisolated static func daemonHome() -> String {
        if let envHome = ProcessInfo.processInfo.environment["HAPPYRANCH_DAEMON_HOME"] {
            return envHome
        }
        let home = NSHomeDirectory()
        // Bundled mode: own app-support directory so the app's runtime
        // (port file, DB, logs, config) is isolated from dev data.
        if packagingMode() == "bundled" {
            return "\(home)/Library/Application Support/HappyRanch"
        }
        return "\(home)/.happyranch"
    }

    private func daemonHome() -> String { AppDelegate.daemonHome() }

    // MARK: - External daemon discovery

    private func discoverExistingDaemon() {
        let home = daemonHome()
        let portFile = URL(fileURLWithPath: "\(home)/daemon.port")
        let pidFile = URL(fileURLWithPath: "\(home)/daemon.pid")

        let reader = PortReader()

        // Try to read port
        guard let port = try? reader.readPort(from: portFile) else {
            return // No port file = daemon not running
        }

        // Try to read PID
        let pidString = try? String(contentsOf: pidFile, encoding: .utf8)
        let pid = pidString.flatMap { Int32($0.trimmingCharacters(in: .whitespacesAndNewlines)) }

        if let pid = pid {
            // Check if the process is actually running
            if processIsAlive(pid: pid) {
                // External daemon detected
                supervisor.onExternalDaemonDetected(pid: pid, port: port)
                refreshDerivedState()

                // Probe health before loading the URL
                Task {
                    await probeAndLoad(port: port)
                }
                return
            } else {
                // Stale PID
                supervisor.onStalePidDetected(pid: pid)
                refreshDerivedState()
                return
            }
        }
    }

    // MARK: - Daemon actions

    /// Restart the managed daemon: stop then start.
    /// Only valid for app-managed daemons; external daemons are never restarted.
    ///
    /// The restart is genuinely two-phase: the stop is issued synchronously,
    /// and a pending-restart flag instructs the termination-completion path
    /// (which settles the supervisor to .stopped ASYNCHRONOUSLY) to perform
    /// the follow-on start.  This fixes the previous bug where the synchronous
    /// canStart check after stopDaemon() was always false because the
    /// supervisor was still .stopping.
    func restartDaemon() {
        guard supervisor.isManagedBySelf, canStop else { return }
        pendingRestart = true
        stopDaemon(confirmed: true)
    }

    func startDaemon() {
        // Always clear the restart flag — a direct start supersedes any
        // pending restart (safety net; the termination handler clears it
        // before issuing the follow-on start, but an unrelated start while
        // waiting for a restart's termination handler shouldn't leave a
        // stale flag).
        pendingRestart = false
        do {
            try supervisor.start()
            refreshDerivedState()
            diagnostics.recordStartCommand(Self.startCommandForCurrentMode())

            // Launch the daemon process
            launchDaemonProcess()
        } catch {
            stateText = "Error: \(error.localizedDescription)"
            refreshDerivedState()
        }
    }

    func stopDaemon(confirmed: Bool = false) {
        do {
            try supervisor.stop(confirmed: confirmed)
            refreshDerivedState()

            // Only terminate the managed process; external daemons are never touched
            if supervisor.isManagedBySelf {
                terminateManagedProcess()
            }
        } catch DaemonSupervisorError.externalStopRequiresConfirmation {
            stateText = "Stop requires confirmation for external daemon"
            refreshDerivedState()
        } catch {
            stateText = "Error: \(error.localizedDescription)"
            refreshDerivedState()
        }
    }

    func stopDaemonWithConfirmation() {
        stopDaemon(confirmed: true)
    }

    // MARK: - Packaging mode

    /// Test seam: override in tests to simulate bundled mode without setting
    /// the real process environment.  Production code never sets this.
    /// Lock-protected to prevent parallel-test races (FINDING 2 fix).
    nonisolated(unsafe) private static var __testPackagingMode: String?
    nonisolated private static let _testPackagingModeLock = NSLock()

    nonisolated static var _testPackagingMode: String? {
        get { _testPackagingModeLock.withLock { __testPackagingMode } }
        set { _testPackagingModeLock.withLock { __testPackagingMode = newValue } }
    }

    /// Returns the packaging mode: "bundled" when running inside a .app bundle
    /// with PACKAGING_MODE=bundled, "dev" otherwise.
    nonisolated static func packagingMode() -> String {
        if let override = _testPackagingMode { return override }
        return ProcessInfo.processInfo.environment["PACKAGING_MODE"] ?? "dev"
    }

    /// Returns the display string for the start command in the current mode.
    nonisolated static func startCommandForCurrentMode() -> String {
        if packagingMode() == "bundled" {
            return "Contents/Resources/daemon/happyranch-daemon"
        }
        return "uv run python -m runtime.daemon"
    }

    /// Returns the filesystem path to the frozen daemon binary inside the .app bundle.
    /// Bundle.main.resourceURL is the Contents/Resources directory.
    nonisolated static func bundledDaemonPath() -> String? {
        guard let resourceURL = Bundle.main.resourceURL else { return nil }
        return resourceURL
            .appendingPathComponent("daemon")
            .appendingPathComponent("happyranch-daemon")
            .path
    }

    /// Returns the filesystem path to the bundled web/dist directory inside the .app bundle.
    nonisolated static func bundledWebDistPath() -> String? {
        guard let resourceURL = Bundle.main.resourceURL else { return nil }
        return resourceURL
            .appendingPathComponent("web")
            .appendingPathComponent("dist")
            .path
    }

    // MARK: - Process management

    private func launchDaemonProcess() {
        let pc = processController
        let mode = Self.packagingMode()

        if mode == "bundled" {
            launchBundledDaemon(pc: pc)
        } else {
            launchDevDaemon(pc: pc)
        }
    }

    /// Launch the frozen daemon binary from inside the .app bundle (bundled mode).
    private func launchBundledDaemon(pc: ProcessControlling) {
        guard let daemonPath = Self.bundledDaemonPath() else {
            stateText = "Bundled daemon not found in app bundle"
            return
        }

        var childEnv = EnvironmentSanitizer.buildChildEnvironment(
            daemonHome: daemonHome(),
            parentEnvironment: ProcessInfo.processInfo.environment
        )
        // In bundled mode, point HAPPYRANCH_WEB_DIST at the bundled web/dist.
        if let webDistPath = Self.bundledWebDistPath() {
            childEnv["HAPPYRANCH_WEB_DIST"] = webDistPath
        }
        // Bind a random free 127.0.0.1 port so the app runs alongside a dev daemon on 8765.
        childEnv["HAPPYRANCH_DAEMON_PORT"] = "0"

        // Ensure the daemon home directory exists before launching.
        // On a first-ever/clean install, ~/Library/Application Support/HappyRanch
        // may not exist, causing Process to throw NSFileNoSuchFileError
        // ("The file 'HappyRanch' doesn't exist") when currentDirectoryURL
        // points to a nonexistent path.
        _ = try? FileManager.default.createDirectory(atPath: daemonHome(), withIntermediateDirectories: true, attributes: nil)

        do {
            let handle = try pc.launch(
                executableURL: URL(fileURLWithPath: daemonPath),
                arguments: [],
                currentDirectoryURL: URL(fileURLWithPath: daemonHome()),
                environment: childEnv,
                terminationHandler: { @Sendable [weak self] exitedHandle in
                    let exitCode = exitedHandle.terminationStatus
                    let signal = exitedHandle.terminationReason == .uncaughtSignal ? 1 : nil as Int32?
                    let stderr = exitedHandle.capturedStandardError
                    let stdout = exitedHandle.capturedStandardOutput
                    Task { @MainActor [weak self] in
                        guard let self else { return }
                        if let ch = self.currentHandle,
                           ch.processIdentifier != exitedHandle.processIdentifier {
                            return
                        }
                        if let stderr = stderr {
                            self.diagnostics.recordDaemonStderr(stderr)
                        }
                        if let stdout = stdout {
                            self.diagnostics.recordDaemonStdout(stdout)
                        }
                        self.supervisor.onProcessExited(exitCode: exitCode, signal: signal)
                        self.diagnostics.recordExit(exitCode: exitCode, signal: signal)
                        self.refreshDerivedState()
                        if self.pendingRestart {
                            self.pendingRestart = false
                            self.startDaemon()
                        }
                    }
                }
            )
            currentHandle = handle
            let pid = handle.processIdentifier

            diagnostics.recordDaemonState(pid: pid, port: 0, bindHost: "127.0.0.1", state: "starting")

            Task {
                await healthProbeLoop(pid: pid)
            }
        } catch {
            currentHandle = nil
            diagnostics.recordLaunchLog("Launch failed (bundled): \(error.localizedDescription)")
            stateText = "Launch failed: \(error.localizedDescription)"
            supervisor.onProcessExited(exitCode: -1, signal: nil)
            refreshDerivedState()
        }
    }

    /// Launch the daemon via `uv run` from the repo root (dev mode).
    private func launchDevDaemon(pc: ProcessControlling) {
        // Ensure the daemon home directory exists before launching.
        // Even though dev mode uses repoRoot() as cwd, the daemon still
        // receives HAPPYRANCH_DAEMON_HOME and needs that directory to exist
        // for its own internal initialization.
        _ = try? FileManager.default.createDirectory(atPath: daemonHome(), withIntermediateDirectories: true, attributes: nil)

        do {
            let handle = try pc.launch(
                executableURL: URL(fileURLWithPath: "/usr/bin/env"),
                arguments: ["uv", "run", "python", "-m", "runtime.daemon"],
                currentDirectoryURL: URL(fileURLWithPath: repoRoot()),
                environment: EnvironmentSanitizer.buildChildEnvironment(
                    daemonHome: daemonHome(),
                    parentEnvironment: ProcessInfo.processInfo.environment
                ),
                terminationHandler: { @Sendable [weak self] exitedHandle in
                    let exitCode = exitedHandle.terminationStatus
                    let signal = exitedHandle.terminationReason == .uncaughtSignal ? 1 : nil as Int32?
                    let stderr = exitedHandle.capturedStandardError
                    let stdout = exitedHandle.capturedStandardOutput
                    Task { @MainActor [weak self] in
                        guard let self else { return }
                        // PID guard: reject only if currentHandle is set AND
                        // doesn't match. If currentHandle is nil (immediate
                        // exit before the caller stores the returned handle),
                        // this is the current launch's callback — accept it.
                        if let ch = self.currentHandle,
                           ch.processIdentifier != exitedHandle.processIdentifier {
                            return
                        }
                        if let stderr = stderr {
                            self.diagnostics.recordDaemonStderr(stderr)
                        }
                        if let stdout = stdout {
                            self.diagnostics.recordDaemonStdout(stdout)
                        }
                        self.supervisor.onProcessExited(exitCode: exitCode, signal: signal)
                        self.diagnostics.recordExit(exitCode: exitCode, signal: signal)
                        self.refreshDerivedState()

                        // Restart continuation: if a restart was requested,
                        // the termination-completion path performs the
                        // follow-on start now that the supervisor has settled.
                        if self.pendingRestart {
                            self.pendingRestart = false
                            self.startDaemon()
                        }
                    }
                }
            )
            currentHandle = handle
            let pid = handle.processIdentifier

            diagnostics.recordDaemonState(pid: pid, port: 0, bindHost: "127.0.0.1", state: "starting")

            // Start health probing loop
            Task {
                await healthProbeLoop(pid: pid)
            }
        } catch {
            currentHandle = nil
            diagnostics.recordLaunchLog("Launch failed (dev): \(error.localizedDescription)")
            stateText = "Launch failed: \(error.localizedDescription)"
            supervisor.onProcessExited(exitCode: -1, signal: nil)
            refreshDerivedState()
        }
    }

    /// Send SIGTERM to the managed daemon and wait for exit.
    /// Escalates (forces state to crashed) if the process doesn't exit within a bounded wait.
    func terminateManagedProcess() {
        guard let handle = currentHandle, handle.isRunning else {
            return
        }

        try? supervisor.stop()
        refreshDerivedState()

        handle.terminate() // SIGTERM

        // Bounded wait for the process to exit
        let deadline = Date().addingTimeInterval(5.0)
        while handle.isRunning && Date() < deadline {
            RunLoop.current.run(until: Date(timeIntervalSinceNow: 0.1))
        }

        if handle.isRunning {
            // Escalate: process didn't respond to SIGTERM
            diagnostics.recordExit(exitCode: -1, signal: 9)
            supervisor.forceState(.crashed)
            refreshDerivedState()
        }
    }

    private func repoRoot() -> String {
        // The app is run from the happyranch repo root
        if let envRoot = ProcessInfo.processInfo.environment["HAPPYRANCH_REPO_ROOT"] {
            return envRoot
        }
        return FileManager.default.currentDirectoryPath
    }

    // MARK: - Health probe loop

    private func healthProbeLoop(pid: Int32) async {
        let home = daemonHome()
        let portFile = URL(fileURLWithPath: "\(home)/daemon.port")
        let reader = PortReader()

        // Poll for port file and health check
        for _ in 0..<30 { // 30 attempts, ~15 seconds total
            guard supervisor.state == .starting || supervisor.state == .unhealthy else {
                break
            }

            // Try to read the port
            if let port = try? reader.readPort(from: portFile) {
                let baseURL = localTransport.baseURL(for: port)
                let probe = HealthProbe(baseURL: baseURL)
                let (success, latencyMs, errorMessage) = await probe.check()

                await MainActor.run {
                    if success {
                        let wasRecovering = (supervisor.state != .running)
                        supervisor.onHealthCheckPassed(pid: pid, port: port)
                        diagnostics.recordHealthProbe(success: true, latencyMs: latencyMs, errorMessage: nil)
                        diagnostics.recordDaemonState(pid: pid, port: port, bindHost: "127.0.0.1", state: "running")
                        refreshDerivedState()
                        webViewURL = baseURL
                        if wasRecovering {
                            dismissDiagnosticsOnRecovery()
                        }
                    } else {
                        supervisor.onHealthCheckFailed()
                        diagnostics.recordHealthProbe(success: false, latencyMs: latencyMs, errorMessage: errorMessage)
                        refreshDerivedState()
                    }
                }
            }

            // Only continue if still in a state that warrants probing
            guard supervisor.state == .starting || supervisor.state == .unhealthy else {
                break
            }

            try? await Task.sleep(nanoseconds: 500_000_000) // 0.5s
        }
    }

    func probeAndLoad(port: UInt16) async {
        let baseURL = localTransport.baseURL(for: port)
        let probe = HealthProbe(baseURL: baseURL)
        let (success, latencyMs, errorMessage) = await probe.check()

        await MainActor.run {
            if success {
                diagnostics.recordHealthProbe(success: true, latencyMs: latencyMs, errorMessage: nil)
                webViewURL = baseURL
            } else {
                diagnostics.recordHealthProbe(success: false, latencyMs: latencyMs, errorMessage: errorMessage)
            }
        }
    }

    // MARK: - Role preference

    /// Persist the user's role choice and reconfigure the supervisor accordingly.
    ///
    /// - HOME: configures the supervisor with the standard daemon home
    ///   and refreshes derived state (same as the normal launch path).
    /// - CLIENT: resets the supervisor to `.notConfigured` and stops any
    ///   active home connector.
    func setRolePreference(_ preference: ConnectionRolePreference) {
        connectionRolePreference = preference

        switch preference {
        case .home:
            if supervisor.state == .notConfigured {
                supervisor.configure(homeDir: daemonHome())
                refreshDerivedState()
            }
        case .client:
            // Stop any active home connector first
            if let connector = homeConnector {
                connector.stop()
                homeConnector = nil
            }
            // Reset supervisor to notConfigured so the daemon-related
            // UI (controls, health probes) gracefully degrades
            supervisor.forceState(.notConfigured)
            refreshDerivedState()
        case .undetermined:
            break // Should not be persisted; treat as no-op
        }
    }

    // MARK: - A2 Remote connection actions

    /// Start the home connector on the tailnet interface.
    ///
    /// Reads the self 100.x address from TailscaleStatusProvider, configures
    /// the connector with the shared pairing store, and starts listening.
    func startHomeConnector() {
        guard case .home = connectionRole else { return }

        // Fetch tailnet self IP for bindHost validation
        let selfIP: String?
        if let status = try? tailscaleProvider.fetchStatus(),
           let firstIP = status.selfTailscaleIPs.first {
            selfIP = firstIP
            tailnetSelfIP = firstIP
        } else {
            selfIP = nil
            tailnetSelfIP = nil
        }

        // Require a tailnet address to start
        guard let bindHost = selfIP else {
            connectionState = .tailnetNotDetected
            return
        }

        let credentialProvider = LocalTokenCredentialProvider(homeDir: daemonHome())

        let port: UInt16
        // Read daemon port from port file
        let portFile = URL(fileURLWithPath: "\(daemonHome())/daemon.port")
        if let daemonPort = try? PortReader().readPort(from: portFile) {
            port = daemonPort
        } else {
            connectionState = .offline
            return
        }

        let connector = HomeConnector(
            bindHost: bindHost,
            bindPort: homeConnectorPort,
            daemonPort: port,
            credentialProvider: credentialProvider,
            pairedDeviceStore: pairingStore,
            tailnetSelfIP: bindHost
        )

        guard case .stopped = connector.state else {
            connectionState = .offline
            return
        }

        do {
            try connector.start()
            homeConnector = connector
            connectionStateManager.onTailscaleDetected(homeNodeOnline: true)
            connectionState = connectionStateManager.state
        } catch {
            connectionStateManager.onTailscaleDetected(homeNodeOnline: false)
            connectionState = connectionStateManager.state
        }
    }

    /// Stop the home connector.
    func stopHomeConnector() {
        homeConnector?.stop()
        homeConnector = nil
        pairingCode = nil
        connectionStateManager.onTailscaleLost()
        connectionState = connectionStateManager.state
    }

    /// Generate a one-time pairing code and capture the tailnet address.
    func generatePairingCodeAction() {
        guard homeConnector != nil else { return }
        pairingCode = pairingStore.generatePairingCode()
        // Refresh tailnet address in case it changed
        if let status = try? tailscaleProvider.fetchStatus(),
           let firstIP = status.selfTailscaleIPs.first {
            tailnetSelfIP = firstIP
        }
    }

    /// Revoke a paired device by credential.
    func revokeDeviceAction(credential: String) {
        guard let connector = homeConnector else { return }
        _ = connector.revokeDevice(credential: credential)
    }

    /// Connect to a remote home runtime (CLIENT role).
    ///
    /// Starts the client loopback bridge, redeems the pairing code with the
    /// home connector, sets deviceCredential on success, then points the
    /// WebView at the bridge's local URL.
    func connectToRemote() {
        guard case .client = connectionRole else { return }
        guard !clientHomeHost.isEmpty,
              let port = UInt16(clientHomePort),
              !clientPairingCode.isEmpty else {
            clientConnectError = "Please fill in all fields"
            return
        }

        clientConnectError = nil
        isConnecting = true
        connectionStateManager.forceState(.online)  // transient — 'connecting'
        connectionState = connectionStateManager.state

        let bridge = ClientBridge(
            homeConnectorHost: clientHomeHost,
            homeConnectorPort: port
        )

        do {
            try bridge.start()
        } catch {
            isConnecting = false
            clientConnectError = "Failed to start bridge: \(error.localizedDescription)"
            connectionStateManager.onHeartbeatFailed()
            connectionState = connectionStateManager.state
            return
        }

        self.clientBridge = bridge

        // Wait for bridge to be ready, then redeem
        Task {
            // Brief wait for listener to come up
            var waitCount = 0
            while case .stopped = bridge.state, waitCount < 50 {
                try? await Task.sleep(nanoseconds: 50_000_000)
                waitCount += 1
            }

            guard case .running = bridge.state,
                  let bridgePort = bridge.bridgePort else {
                await MainActor.run {
                    isConnecting = false
                    clientConnectError = "Bridge failed to start"
                    bridge.stop()
                    self.clientBridge = nil
                    connectionStateManager.onHeartbeatFailed()
                    connectionState = connectionStateManager.state
                }
                return
            }

            do {
                try await bridge.redeemPairing(
                    code: clientPairingCode,
                    homeHost: clientHomeHost,
                    homePort: port,
                    timeout: 30
                )

                await MainActor.run {
                    isConnecting = false
                    webViewURL = "http://127.0.0.1:\(bridgePort)/"
                    connectionStateManager.onHeartbeatSucceeded()
                    connectionState = connectionStateManager.state
                }
            } catch let error as RedeemPairingError {
                await MainActor.run {
                    isConnecting = false
                    bridge.stop()
                    self.clientBridge = nil
                    switch error {
                    case .refused:
                        clientConnectError = "Refused — invalid or expired pairing code"
                    case .connectionFailed(let msg):
                        clientConnectError = "Connection failed: \(msg)"
                    case .invalidResponse:
                        clientConnectError = "Invalid response from home connector"
                    }
                    connectionStateManager.onHeartbeatFailed()
                    connectionState = connectionStateManager.state
                }
            } catch {
                await MainActor.run {
                    isConnecting = false
                    bridge.stop()
                    self.clientBridge = nil
                    clientConnectError = "Unexpected error: \(error.localizedDescription)"
                    connectionStateManager.onHeartbeatFailed()
                    connectionState = connectionStateManager.state
                }
            }
        }
    }

    /// Disconnect from the remote home runtime (CLIENT role).
    func disconnectRemote() {
        clientBridge?.stop()
        clientBridge = nil
        webViewURL = nil
        clientConnectError = nil
        connectionStateManager.onTailscaleLost()
        connectionState = connectionStateManager.state
    }

    // MARK: - Helpers

    /// Refresh derived @Published properties from the current supervisor state.
    /// Call this after every state change so menu-command bindings stay in sync.
    /// Internal so tests can verify menu-command enable/disable derivation
    /// across all supervisor states.
    func refreshDerivedState() {
        stateText = supervisor.state.description
        let s = supervisor.state
        canStart = (s == .stopped || s == .crashed || s == .stalePid || s == .failed)
        canStop = s.canStop
        canRestart = canStop && supervisor.isManagedBySelf
    }

    /// Dismiss the diagnostics sheet when the daemon recovers to a healthy state.
    /// Called from healthProbeLoop after a successful health check pass during
    /// recovery (non-.running → .running). Internal for test coverage.
    func dismissDiagnosticsOnRecovery() {
        if supervisor.state == .running {
            showDiagnostics = false
        }
    }

    private func processIsAlive(pid: Int32) -> Bool {
        let result = kill(pid, 0)
        return result == 0 || errno == EPERM
    }
}
