import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Plus, RotateCcw, Shield, Trash2, TriangleAlert } from 'lucide-react';
import { Button } from '@/design-system/primitives/Button';
import { Input } from '@/design-system/primitives/Input';
import { Textarea } from '@/design-system/primitives/Textarea';
import { customSkillErrorText, isCustomSkillForbidden, isCustomSkillStaleRevision, type EligibilityRule, useAddCustomSkillVersion, useCustomSkill, useCustomSkillDiff, useCustomSkillEligibility, useCustomSkillVersions, usePatchCustomSkill, usePreviewCustomSkillEligibility, usePurgeCustomSkill, useRestoreCustomSkill, useRetireCustomSkill, useSaveCustomSkillEligibility } from '@/hooks/custom-skills';
import { SkillStatusBadge } from './SkillStatusBadge';
import { CustomSkillsState } from './CustomSkillsPage';

const emptyRule = (): EligibilityRule => ({ scope_type: 'agent', scope_target: '', effect: 'allow' });

export function CustomSkillDetailPage(): JSX.Element {
  const { slug, skillId } = useParams<{ slug: string; skillId: string }>();
  const detail = useCustomSkill(skillId); const versions = useCustomSkillVersions(skillId); const eligibility = useCustomSkillEligibility(skillId);
  const patch = usePatchCustomSkill(); const addVersion = useAddCustomSkillVersion(); const retire = useRetireCustomSkill(); const restore = useRestoreCustomSkill(); const purge = usePurgeCustomSkill(); const preview = usePreviewCustomSkillEligibility(); const saveEligibility = useSaveCustomSkillEligibility();
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [skillMd, setSkillMd] = useState(''); const [rules, setRules] = useState<EligibilityRule[]>([]); const [revision, setRevision] = useState<number | null>(null); const [a, setA] = useState<number>(); const [b, setB] = useState<number>(); const [message, setMessage] = useState<string | null>(null);
  const [confirmingPurge, setConfirmingPurge] = useState(false); const [typedSlug, setTypedSlug] = useState('');
  const initializedRulesForSkill = useRef<string>();
  const diff = useCustomSkillDiff(skillId, a, b);
  useEffect(() => { if (detail.data) { setName(detail.data.name ?? ''); setDescription(detail.data.description ?? ''); } }, [detail.data]);
  useEffect(() => {
    if (!eligibility.data) return;
    setRevision(eligibility.data.revision);
    if (initializedRulesForSkill.current !== skillId) {
      setRules(eligibility.data.rules);
      initializedRulesForSkill.current = skillId;
    }
  }, [eligibility.data, skillId]);
  const back = <Link to={`/orgs/${slug ?? ''}/skills/custom`} className="text-fg-muted hover:text-fg text-body-sm mb-4 inline-flex items-center gap-1.5"><ArrowLeft size={15} />Back to custom skills</Link>;
  if (detail.isLoading) return <div className="mx-auto max-w-5xl p-6">{back}<div className="border-border-subtle bg-surface-subtle h-64 animate-pulse rounded-md border" /></div>;
  if (isCustomSkillForbidden(detail.error)) return <CustomSkillsState icon={<Shield size={28} />} title="Founder access required" body="Custom skill management is restricted to the founder. Agent sessions cannot view or change custom skills." />;
  if (detail.isError || !detail.data) return <CustomSkillsState icon={<TriangleAlert size={28} />} title="Could not load this custom skill" body="This custom skill is unavailable right now. Try again shortly." />;
  const skill = detail.data;
  if (skill.state === 'permanently_removed') return <div className="mx-auto max-w-5xl p-6">{back}<section className="border-border-default bg-surface-raised rounded-md border p-6"><h1 className="text-fg text-lg font-semibold">Permanently removed</h1><p className="text-fg-muted mt-2 text-sm"><span className="font-mono">{skill.slug}</span> is permanently denied and its ID and slug remain reserved.</p><p className="text-fg-muted mt-2 text-sm">This was a logical purge. Historical evidence, packages, artifacts, and links were retained; physical_erasure=false.</p><dl className="text-mono-sm text-fg-muted mt-4"><dt>Purge ID</dt><dd>{skill.purge_id}</dd><dt className="mt-2">Completed</dt><dd>{skill.purged_at}</dd></dl></section></div>;
  const hidden = skill.hidden_reason === 'no_eligibility_policy';
  const runPreview = async () => { setMessage(null); try { await preview.mutateAsync({ skillId: skillId as string, rules }); } catch (error) { setMessage(customSkillErrorText(error, 'Could not preview eligibility impact.')); } };
  const commitEligibility = async () => { if (revision === null) return; setMessage(null); try { const result = await saveEligibility.mutateAsync({ skillId: skillId as string, rules, revision }); setRevision(result.revision); setMessage('Eligibility saved.'); } catch (error) { if (isCustomSkillStaleRevision(error)) { await eligibility.refetch(); setMessage('Eligibility changed elsewhere. The current revision was reloaded; your edits are still here. Review the impact and retry.'); } else setMessage(customSkillErrorText(error, 'Could not save eligibility.')); } };
  return <div className="h-full overflow-y-auto"><div className="mx-auto w-full max-w-5xl px-4 py-5 md:px-7 md:py-6">{back}
    <header className="border-border-default bg-surface-raised rounded-md border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex items-center gap-2"><span className="bg-accent-soft text-accent-text text-2xs rounded-full px-2 py-0.5 font-bold tracking-wide uppercase">custom</span><SkillStatusBadge state={hidden ? 'no_eligibility_policy' : skill.validation_state ?? 'unknown'} />{skill.retired_at && <span className="text-mono-sm text-fg-muted">Retired</span>}</div><h1 className="text-fg font-mono text-lg font-semibold">{skill.name}</h1><p className="text-fg-muted text-body-sm mt-2">{skill.description || 'No description provided.'}</p></div><div className="flex gap-2"><Button variant={skill.retired_at ? 'secondary' : 'destructive'} onClick={() => skill.retired_at ? restore.mutate(skillId as string) : retire.mutate({ skillId: skillId as string })} disabled={retire.isPending || restore.isPending}>{skill.retired_at ? <><RotateCcw />Restore</> : 'Retire'}</Button>{skill.retired_at && <Button variant="destructive" onClick={() => setConfirmingPurge(true)}><Trash2 />Permanently remove</Button>}</div></div></header>
    {confirmingPurge && <section role="dialog" aria-modal="true" aria-labelledby="purge-title" className="border-danger-border bg-surface-raised mt-4 rounded-md border p-5"><h2 id="purge-title" className="text-fg font-semibold">Permanently remove {skill.slug}</h2><p className="text-fg-muted mt-2 text-sm">This irreversible logical purge permanently denies serving and reserves the ID and slug. It does not erase historical evidence, packages, artifacts, links, backups, or logs (physical_erasure=false).</p><label className="mt-4 block text-sm">Type <span className="font-mono">{skill.slug}</span> to confirm<Input autoFocus value={typedSlug} onChange={(e) => setTypedSlug(e.target.value)} /></label>{purge.isError && <p role="alert" className="text-danger-text mt-2 text-sm">{customSkillErrorText(purge.error, 'Permanent removal failed.')}</p>}<div className="mt-4 flex gap-2"><Button variant="destructive" disabled={typedSlug !== skill.slug || purge.isPending} onClick={() => purge.mutate({ skillId: skillId as string, typedSlug })}>{purge.isPending ? 'Removing…' : 'Permanently remove'}</Button><Button variant="secondary" onClick={() => setConfirmingPurge(false)} disabled={purge.isPending}>Cancel</Button></div></section>}
    <section className="border-border-default bg-surface-raised mt-4 rounded-md border p-5"><h2 className="text-fg text-sm font-semibold">Metadata</h2><div className="mt-3 grid gap-3 md:grid-cols-2"><label className="text-sm">Name<Input value={name} onChange={(e) => setName(e.target.value)} /></label><label className="text-sm">Description<Input value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><Button className="mt-3" variant="secondary" onClick={() => patch.mutate({ skillId: skillId as string, body: { name, description } })} disabled={patch.isPending}>Save metadata</Button></section>
    <section aria-labelledby="current-guidance-heading" className="border-border-default bg-surface-raised mt-4 rounded-md border p-5"><h2 id="current-guidance-heading" className="text-fg text-sm font-semibold">Current guidance / SKILL.md</h2><p className="text-fg-muted text-body-sm mt-1">Current immutable guidance source.</p><dl className="text-mono-sm text-fg-muted mt-3 flex flex-wrap gap-x-4 gap-y-1"><div><dt className="inline">Current version: </dt><dd className="inline">v{skill.current_version_id}</dd></div><div><dt className="inline">Content hash: </dt><dd className="inline">{skill.content_hash ?? 'Unavailable'}</dd></div></dl>{skill.skill_md_cache == null ? <p className="text-fg-muted text-body-sm mt-3">No current SKILL.md content is available.</p> : <pre className="bg-bg-subtle text-mono-sm mt-3 max-h-80 overflow-auto rounded-md p-3">{skill.skill_md_cache}</pre>}</section>
    <section className="border-border-default bg-surface-raised mt-4 rounded-md border p-5"><h2 className="text-fg text-sm font-semibold">Add version</h2><p className="text-fg-muted text-body-sm mt-1">Saving a version validates its guidance. Eligibility remains visibility-only.</p><Textarea className="mt-3" value={skillMd} onChange={(e) => setSkillMd(e.target.value)} placeholder="SKILL.md content" /><Button className="mt-3" onClick={() => addVersion.mutate({ skillId: skillId as string, skill_md: skillMd })} disabled={!skillMd || addVersion.isPending}>Save new version</Button></section>
    <EligibilityEditor rules={rules} setRules={setRules} preview={preview.data} loading={eligibility.isLoading} revision={revision} onPreview={runPreview} onSave={commitEligibility} saving={saveEligibility.isPending} message={message} />
    <section className="border-border-default bg-surface-raised mt-4 rounded-md border p-5"><h2 className="text-fg text-sm font-semibold">Version history</h2>{versions.isLoading ? <div className="bg-surface-subtle mt-3 h-16 animate-pulse rounded-md" /> : versions.isError ? <p className="text-attention-text mt-3 text-sm">Could not load version history.</p> : <><div className="mt-3 flex flex-wrap gap-3"><label className="text-sm">Before<select className="border-border-default bg-surface-raised ml-2 rounded-md border p-2" value={a ?? ''} onChange={(e) => setA(e.target.value === '' ? undefined : Number(e.target.value))}><option value="">Choose version</option>{versions.data?.versions.map((v) => <option key={v.id} value={v.id}>v{v.id}</option>)}</select></label><label className="text-sm">After<select className="border-border-default bg-surface-raised ml-2 rounded-md border p-2" value={b ?? ''} onChange={(e) => setB(e.target.value === '' ? undefined : Number(e.target.value))}><option value="">Choose version</option>{versions.data?.versions.map((v) => <option key={v.id} value={v.id}>v{v.id}</option>)}</select></label></div><ul className="text-fg-muted text-body-sm mt-4 space-y-2">{versions.data?.versions.map((v) => <li key={v.id} className="border-border-subtle flex flex-wrap justify-between gap-2 border-t pt-2"><span>v{v.id} · {v.validation_state ?? 'validation unknown'}</span><span className="text-mono-sm">{v.content_hash}</span></li>)}</ul>{diff.isFetching && <p className="text-fg-muted mt-3 text-sm">Loading diff…</p>}{diff.data && <pre className="bg-bg-subtle text-mono-sm mt-3 max-h-80 overflow-auto rounded-md p-3">{diff.data.diff.join('\n') || 'No content changes.'}</pre>}{diff.isError && <p className="text-attention-text mt-3 text-sm">Could not load that version diff.</p>}</>}</section>
  </div></div>;
}

function EligibilityEditor({ rules, setRules, preview, loading, revision, onPreview, onSave, saving, message }: { rules: EligibilityRule[]; setRules: React.Dispatch<React.SetStateAction<EligibilityRule[]>>; preview: { newly_visible: string[]; newly_hidden: string[]; unchanged: string[] } | undefined; loading: boolean; revision: number | null; onPreview: () => void; onSave: () => void; saving: boolean; message: string | null }): JSX.Element {
  return <section className="border-border-default bg-surface-raised mt-4 rounded-md border p-5"><h2 className="text-fg text-sm font-semibold">Eligibility</h2><p className="text-fg-muted text-body-sm mt-1">Controls guidance visibility only. It does not grant permissions, tools, credentials, or authentication.</p>{revision !== null && <p className="text-fg-muted mt-2 text-sm">Current revision: v{revision}</p>}{loading ? <div className="bg-surface-subtle mt-3 h-20 animate-pulse rounded-md" /> : <><div className="mt-4 space-y-2">{rules.map((rule, index) => <div key={index} className="flex flex-wrap items-center gap-2"><select aria-label={`Rule ${index + 1} scope`} className="border-border-default bg-surface-raised rounded-md border p-2 text-sm" value={rule.scope_type} onChange={(e) => setRules((old) => old.map((r, i) => i === index ? { ...r, scope_type: e.target.value as EligibilityRule['scope_type'] } : r))}><option value="agent">Agent</option><option value="team">Team</option><option value="org">Organization</option></select><Input aria-label={`Rule ${index + 1} target`} className="max-w-sm" value={rule.scope_target ?? ''} onChange={(e) => setRules((old) => old.map((r, i) => i === index ? { ...r, scope_target: e.target.value } : r))} placeholder="Agent or team name" /><select aria-label={`Rule ${index + 1} effect`} className="border-border-default bg-surface-raised rounded-md border p-2 text-sm" value={rule.effect} onChange={(e) => setRules((old) => old.map((r, i) => i === index ? { ...r, effect: e.target.value as EligibilityRule['effect'] } : r))}><option value="allow">Allow</option><option value="deny">Deny</option></select><Button type="button" variant="ghost" size="sm" onClick={() => setRules((old) => old.filter((_, i) => i !== index))}>Remove</Button></div>)}</div><Button type="button" variant="secondary" className="mt-3" onClick={() => setRules((old) => [...old, emptyRule()])}><Plus />Add rule</Button><div className="mt-4 flex flex-wrap gap-2"><Button type="button" variant="secondary" onClick={onPreview}>Preview impact</Button><Button type="button" onClick={onSave} disabled={saving}>{saving ? 'Saving…' : 'Save eligibility'}</Button></div>{preview && <div className="border-border-subtle bg-bg-subtle text-body-sm mt-4 grid gap-3 rounded-md border p-3 md:grid-cols-3"><Impact title="Newly visible" names={preview.newly_visible} /><Impact title="Newly hidden" names={preview.newly_hidden} /><Impact title="Unchanged" names={preview.unchanged} /></div>}{message && <p role="status" className="text-fg-muted mt-3 text-sm">{message}</p>}</>}</section>;
}
function Impact({ title, names }: { title: string; names: string[] }): JSX.Element { return <div><h3 className="text-fg text-xs font-semibold">{title} · {names.length}</h3><p className="text-fg-muted mt-1 text-xs">{names.join(', ') || 'None'}</p></div>; }
