export const KB_STRINGS = {
  pageTitle: 'Knowledge base',
  searchPlaceholder: 'Search entries…',
  composeButton: 'Compose…',
  emptyListTitle: 'No entries',
  emptyListBody: 'No KB entries match the current filters.',
  emptySearchTitle: 'No matches',
  emptySearchBody: 'No entries match that search.',
  drawerLoading: 'Loading entry…',
  filterAll: 'All',
  filterTypes: 'Types',
  filterTags: 'Tags',
  authoredBy: (agent: string) => `Authored by ${agent}`,
  sourceTaskLabel: 'Source task:',
  relatedEntriesLabel: 'Related entries:',
  composeDialogTitle: 'Compose KB entry',
  composeDialogSubmit: 'Add entry',
  composeDialogCancel: 'Cancel',
};
