"""First-party adapter for Claude Code (THR-107 Phase 1 / D2).

Private implementation detail of the adapter runtime boundary — not a
plugin surface. This adapter encapsulates Claude-specific argv construction
behind :meth:`build_argv`.
"""

from __future__ import annotations


class ClaudeAdapter:
    """First-party adapter for Claude Code's headless ``-p`` mode.

    Encapsulates argv construction: binary, optional model flag,
    permission-mode, allowed-tools, output-format, and optional resume
    session. Every element and order is pinned to the Phase-0
    cmd-baseline contract except the prompt transport: THR-200 moved the
    prompt body OFF argv onto stdin (the CLI reads the user prompt from
    stdin when ``-p`` is given without a message argument), so large
    thread prompts no longer hit the kernel per-argument E2BIG cliff.
    The caller delivers the prompt via ``input_text`` on the subprocess.
    """

    def build_argv(
        self,
        cli_path: str,
        prompt: str,
        permission_mode: str,
        allowed_tools: str,
        model: str | None = None,
        model_arg: list[str] | None = None,
        resume_session_id: str | None = None,
    ) -> list[str]:
        """Build the argv list for a Claude Code subprocess launch.

        Args:
            cli_path: Resolved absolute path to the ``claude`` binary.
            prompt: Full prompt text including session-lifetime preamble.
                Delivered via stdin (``input_text``), never argv (THR-200).
            permission_mode: ``--permission-mode`` value from Settings.
            allowed_tools: Space-separated allow-rule string (generated by
                ``allow_rules_for_agent`` in the workspace adapter).
            model: Agent model id to inject, or None for CLI default.
            model_arg: Model arg template ``[flag, placeholder]`` or None.
            resume_session_id: Agent CLI session id for ``--resume``.
        """
        cmd: list[str] = [cli_path]
        if model and model_arg:
            for elem in model_arg:
                cmd.append(elem.replace("{model}", model))
        cmd += [
            "-p",
            "--permission-mode",
            permission_mode,
            "--allowedTools",
            allowed_tools,
            "--output-format",
            "json",
        ]
        if resume_session_id:
            cmd += ["--resume", resume_session_id]
        return cmd
